services:
  quasar:
    build: .
    volumes:
      - .:/app
    ports:
      - "9000:9000"
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true  # Garante hot reload no Docker
